- name: Cloud Run
  # You may pin to the exact commit or the version.
  # uses: stefda/action-cloud-run@aadc6cdc54fcfb307ac3cadc158ec2c08924ac42
  uses: stefda/action-cloud-run@v1.8
  with:
    # Name of the docker image
    image: 
    # Name of the service in Cloud Run
    service: 
    # GCP project
    project: 
    # GCP region
    region: 
    # GCP service key with storage and run permissions
    service key: 
    # CloudSQL instance name
    cloud sql: # optional
    # Path to .env file which will be added to the Cloud Run deployment
    env: # optional
    # VPC connector name
    vpc connector: # optional
